exports.DOESDIRECTORYEXIST = "DOESDIRECTORYEXIST";
exports.DOESDIRECTORYEXISTRESPONSE = "DOESDIRECTORYEXISTRESPONSE";

exports.CREATEDIRECTORY = "CREATEDIRECTORY";
exports.CREATEDIRECTORYRESPOMSE = "CREATEDIRECTORYRESPOMSE";

exports.REMOVEADDONSMAKEFILE = "REMOVEADDONSMAKEFILE";
exports.REMOVEADDONSMAKEFILERESPONSE = "REMOVEADDONSMAKEFILERESPONSE";

exports.WRITEJSONFILE = "WRITEJSONFILE";
exports.WRITEJSONFILERESPONSE = "WRITEJSONFILERESPONSE";

exports.READJSONFILE = "READJSONFILE";
exports.READJSONFILERESPONSE = "READJSONFILEREADJSONFILERESPONSE";

exports.READFRONTENDCONFIG = "READFRONTENDCONFIG";
exports.READFRONTENDCONFIGRESPONSE = "READFRONTENDCONFIGRESPONSE";

exports.WRITEFRONTENDCONFIG = "WRITEFRONTENDCONFIG";
exports.WRITEFRONTENDCONFIGRESPONSE = "WRITEFRONTENDCONFIG";

exports.READCLICONFIG = "READCLICONFIG";
exports.READCLICONFIGRESPONSE = "READCLICONFIGRESPONSE";

exports.GETPLATFORM = "GETPLATFORM";
exports.GETPLATFORMRESPONSE = "GETPLATFORMRESPONSE";

exports.GETTEMPLATES = "GETTEMPLATES";
exports.GETTEMPLATESRESPONSE = "GETTEMPLATESRESPONSE";

exports.READHISTORY = "READHISTORY";
exports.READHISTORYRESPONSE = "READHISTORYRESPONSE";

exports.ADDTOHISTORY = "ADDTOHISTORY";
exports.ADDTOHISTORYRESPONSE = "ADDTOHISTORYRESPONSE";

// ofPackageManager
exports.GETCLIVERSION = "GETCLIVERSION";
exports.GETCLIVERSIONRESPONSE = "GETCLIVERSIONRESPONSE";
